apiVersion: v1
kind: ConfigMap
metadata:
  name: geneweaver-legacy-config
data:
  AUTH_CLIENTID: "x9IiBRyt8lS3lsqrz2H6aO1leRBbxyb7"
  APPLICATION_RESULTS: "/var/geneweaver/results"
  CELERY_HOST: "redis-master"
  CELERY_PORT: "6379"
  CELERY_TRANSPORT: "redis"
  CELERY_DB: "0"
  CELERY_BACKEND: "redis://redis-master:6379/0"